/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	dnsv1 "github.com/estaleiro/dns-controller/pkg/apis/dns/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNSRecords implements DNSRecordInterface
type FakeDNSRecords struct {
	Fake *FakeEstaleiroV1
	ns   string
}

var dnsrecordsResource = schema.GroupVersionResource{Group: "estaleiro.io", Version: "v1", Resource: "dnsrecords"}

var dnsrecordsKind = schema.GroupVersionKind{Group: "estaleiro.io", Version: "v1", Kind: "DNSRecord"}

// Get takes name of the dNSRecord, and returns the corresponding dNSRecord object, and an error if there is any.
func (c *FakeDNSRecords) Get(name string, options v1.GetOptions) (result *dnsv1.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dnsrecordsResource, c.ns, name), &dnsv1.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dnsv1.DNSRecord), err
}

// List takes label and field selectors, and returns the list of DNSRecords that match those selectors.
func (c *FakeDNSRecords) List(opts v1.ListOptions) (result *dnsv1.DNSRecordList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dnsrecordsResource, dnsrecordsKind, c.ns, opts), &dnsv1.DNSRecordList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &dnsv1.DNSRecordList{ListMeta: obj.(*dnsv1.DNSRecordList).ListMeta}
	for _, item := range obj.(*dnsv1.DNSRecordList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNSRecords.
func (c *FakeDNSRecords) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dnsrecordsResource, c.ns, opts))

}

// Create takes the representation of a dNSRecord and creates it.  Returns the server's representation of the dNSRecord, and an error, if there is any.
func (c *FakeDNSRecords) Create(dNSRecord *dnsv1.DNSRecord) (result *dnsv1.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dnsrecordsResource, c.ns, dNSRecord), &dnsv1.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dnsv1.DNSRecord), err
}

// Update takes the representation of a dNSRecord and updates it. Returns the server's representation of the dNSRecord, and an error, if there is any.
func (c *FakeDNSRecords) Update(dNSRecord *dnsv1.DNSRecord) (result *dnsv1.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dnsrecordsResource, c.ns, dNSRecord), &dnsv1.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dnsv1.DNSRecord), err
}

// Delete takes name of the dNSRecord and deletes it. Returns an error if one occurs.
func (c *FakeDNSRecords) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dnsrecordsResource, c.ns, name), &dnsv1.DNSRecord{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNSRecords) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dnsrecordsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &dnsv1.DNSRecordList{})
	return err
}

// Patch applies the patch and returns the patched dNSRecord.
func (c *FakeDNSRecords) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *dnsv1.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dnsrecordsResource, c.ns, name, pt, data, subresources...), &dnsv1.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dnsv1.DNSRecord), err
}
