/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/estaleiro/dns-controller/pkg/apis/dns/v1"
	scheme "github.com/estaleiro/dns-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DNSRecordsGetter has a method to return a DNSRecordInterface.
// A group's client should implement this interface.
type DNSRecordsGetter interface {
	DNSRecords(namespace string) DNSRecordInterface
}

// DNSRecordInterface has methods to work with DNSRecord resources.
type DNSRecordInterface interface {
	Create(*v1.DNSRecord) (*v1.DNSRecord, error)
	Update(*v1.DNSRecord) (*v1.DNSRecord, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.DNSRecord, error)
	List(opts metav1.ListOptions) (*v1.DNSRecordList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.DNSRecord, err error)
	DNSRecordExpansion
}

// dNSRecords implements DNSRecordInterface
type dNSRecords struct {
	client rest.Interface
	ns     string
}

// newDNSRecords returns a DNSRecords
func newDNSRecords(c *EstaleiroV1Client, namespace string) *dNSRecords {
	return &dNSRecords{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dNSRecord, and returns the corresponding dNSRecord object, and an error if there is any.
func (c *dNSRecords) Get(name string, options metav1.GetOptions) (result *v1.DNSRecord, err error) {
	result = &v1.DNSRecord{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsrecords").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DNSRecords that match those selectors.
func (c *dNSRecords) List(opts metav1.ListOptions) (result *v1.DNSRecordList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DNSRecordList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsrecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dNSRecords.
func (c *dNSRecords) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dnsrecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a dNSRecord and creates it.  Returns the server's representation of the dNSRecord, and an error, if there is any.
func (c *dNSRecords) Create(dNSRecord *v1.DNSRecord) (result *v1.DNSRecord, err error) {
	result = &v1.DNSRecord{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dnsrecords").
		Body(dNSRecord).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dNSRecord and updates it. Returns the server's representation of the dNSRecord, and an error, if there is any.
func (c *dNSRecords) Update(dNSRecord *v1.DNSRecord) (result *v1.DNSRecord, err error) {
	result = &v1.DNSRecord{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dnsrecords").
		Name(dNSRecord.Name).
		Body(dNSRecord).
		Do().
		Into(result)
	return
}

// Delete takes name of the dNSRecord and deletes it. Returns an error if one occurs.
func (c *dNSRecords) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsrecords").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dNSRecords) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsrecords").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dNSRecord.
func (c *dNSRecords) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.DNSRecord, err error) {
	result = &v1.DNSRecord{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dnsrecords").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
