apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dnszones.estaleiro.io
spec:
  group: estaleiro.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: dnszones
    singular: dnszone
    kind: DNSZone
    shortNames:
    - dz
  validation: 
     openAPIV3Schema:
      properties:
        metadata:
         properties:
            name:
              type: string
              pattern: '^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-z0-9]{2,}$'
        spec:
         properties:
            refresh:
              type: integer
              description: "The zone Refresh time in seconds" 
              minimum: 30
            retry:
              type: integer
              description: "The zone Retry time in seconds"
              minimum: 30
            expire:
              type: integer
              description: "The zone Expiration time in seconds"
              minimum: 30

